// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSXcf___-duN7ATv5PLRYjy9yl_R6w-JE',
    appId: '1:609596938598:web:5791cb06f3eceb083490a7',
    messagingSenderId: '609596938598',
    projectId: 'pixelplay-5adfb',
    authDomain: 'pixelplay-5adfb.firebaseapp.com',
    storageBucket: 'pixelplay-5adfb.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDX1blfnmd8g-FGxt7jiIn_USrmISfAWGQ',
    appId: '1:609596938598:android:4dd885e9cd32675a3490a7',
    messagingSenderId: '609596938598',
    projectId: 'pixelplay-5adfb',
    storageBucket: 'pixelplay-5adfb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBSkUBtliJAHmSO2aex2AcR6TK7zFUbRA',
    appId: '1:609596938598:ios:709ee65ecb3838053490a7',
    messagingSenderId: '609596938598',
    projectId: 'pixelplay-5adfb',
    storageBucket: 'pixelplay-5adfb.firebasestorage.app',
    iosBundleId: 'com.example.pixelplayapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBSkUBtliJAHmSO2aex2AcR6TK7zFUbRA',
    appId: '1:609596938598:ios:709ee65ecb3838053490a7',
    messagingSenderId: '609596938598',
    projectId: 'pixelplay-5adfb',
    storageBucket: 'pixelplay-5adfb.firebasestorage.app',
    iosBundleId: 'com.example.pixelplayapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCSXcf___-duN7ATv5PLRYjy9yl_R6w-JE',
    appId: '1:609596938598:web:d72d1189160830bc3490a7',
    messagingSenderId: '609596938598',
    projectId: 'pixelplay-5adfb',
    authDomain: 'pixelplay-5adfb.firebaseapp.com',
    storageBucket: 'pixelplay-5adfb.firebasestorage.app',
  );
}
